Rails 5 support
sikachu/verification pull request #7
Opened 2016-12-16 08:15 UTC by webhoernchen

- Support for Rails 5 added
- Deprecation Warning for before_filter in Rails 5 fixed

2016-12-16 14:10 UTC, sikachu requested changes
There's one thing that needs to be fixed.

Would you mind also rebasing against `master` as I just pushed some commits to fix Travis build? Thanks!

2016-12-16 14:10 UTC, sikachu commented on .gitignore
> +
Do you mind remove changes to this `.gitignore?`

2016-12-16 15:55 UTC, webhoernchen commented on .gitignore
> +
changes are removed

2016-12-17 02:21 UTC, sikachu approved these changes

2016-12-17 02:21 UTC, merged

2016-12-17 02:22 UTC, sikachu commented
Thank you for your patch!